export const baseShrines = [
  "HealingReductionShrineUpgrade",
  "ShopPricesShrineUpgrade",
  "EnemyHealthShrineUpgrade",
  "EnemyDamageShrineUpgrade",
  "EnemySpeedShrineUpgrade",
  "EnemyShieldShrineUpgrade",
  "EnemyCountShrineUpgrade",
  "EnemyRespawnShrineUpgrade",
  "NextBiomeEnemyShrineUpgrade",
  "BiomeSpeedShrineUpgrade",
  "MinibossCountShrineUpgrade",
  "BossDifficultyShrineUpgrade",
  "BoonSkipShrineUpgrade",
  "BoonManaReserveShrineUpgrade",
  "BanUnpickedBoonsShrineUpgrade",
  "LimitGraspShrineUpgrade",
  "EnemyEliteShrineUpgrade",
];

export const shrineObj = {
  EnemyDamageShrineUpgrade: `Pain`,
  EnemyHealthShrineUpgrade: `Grit`,
  EnemyShieldShrineUpgrade: `Wards`,
  EnemySpeedShrineUpgrade: `Frenzy`,
  EnemyCountShrineUpgrade: `Hordes`,
  NextBiomeEnemyShrineUpgrade: `Menace`,
  EnemyRespawnShrineUpgrade: `Return`,
  EnemyEliteShrineUpgrade: `Fangs`,
  HealingReductionShrineUpgrade: `Scars`,
  ShopPricesShrineUpgrade: `Debt`,
  MinibossCountShrineUpgrade: `Shadow`,
  BoonSkipShrineUpgrade: `Forfeit`,
  BiomeSpeedShrineUpgrade: `Time`,
  LimitGraspShrineUpgrade: `Void`,
  BoonManaReserveShrineUpgrade: `Hubris`,
  BanUnpickedBoonsShrineUpgrade: `Denial`,
  BossDifficultyShrineUpgrade: `Rivals`,
};

export const vowDes = {
  Scars: `Any Healing effects are less effective. (100-0%)`,
  Debt: `All items that cost Gold are more expensive. (0-80%)`,
  Grit: `All foes have increased Life. (0-30%)`,
  Pain: `All foes deal increased damage. (0-100%)`,
  Frenzy: `All foes are faster. (0-40%)`,
  Wards: `All foes have increased Barrier. (0-2)`,
  Hordes: `Most Encounters have more foes. (0-60%)`,
  Return: `Most slain foes have chance to become a Revenant. (0-50%)`,
  Menace: `Most foes have chance to be from the next Region. (0-25%)`,
  Time: `You have certain time to fight through each Region. (∞-5.00mins)`,
  Shadow: `All Encounters with Wardens contain no fewer than certain Shadow Servant(s). (0-1)`,
  Rivals: `The Guardian of the certain Region(s) shall be stronger in various ways. (0-4regions)`,
  Forfeit: `The first certain amount of Boon(s) in each Region become Red Onion instead. (0-1)`,
  Hubris: `After you choose a Boon, Prime certain amount of Magick for each Rarity greater than Common. (0-6)`,
  Denial: `After you choose a Boon, certain amount of unpicked blessings shall not appear again this night. (0-2)`,
  Void: `You have access to certain amount of your Grasp for your Arcana. (100-0%)`,
  Fangs: `Most foes with Armor also have certain amount of random Perk(s). (0-2)`,
};

export const shrineID = {
  HealingReductionShrineUpgrade: 1,
  ShopPricesShrineUpgrade: 2,
  EnemyHealthShrineUpgrade: 3,
  EnemyDamageShrineUpgrade: 4,
  EnemySpeedShrineUpgrade: 5,
  EnemyShieldShrineUpgrade: 6,
  EnemyCountShrineUpgrade: 7,
  EnemyRespawnShrineUpgrade: 8,
  NextBiomeEnemyShrineUpgrade: 9,
  BiomeSpeedShrineUpgrade: 10,
  MinibossCountShrineUpgrade: 11,
  BossDifficultyShrineUpgrade: 12,
  BoonSkipShrineUpgrade: 13,
  BoonManaReserveShrineUpgrade: 14,
  BanUnpickedBoonsShrineUpgrade: 15,
  LimitGraspShrineUpgrade: 16,
  EnemyEliteShrineUpgrade: 17,
};

export const idShrine = {
  1: "HealingReductionShrineUpgrade",
  2: "ShopPricesShrineUpgrade",
  3: "EnemyHealthShrineUpgrade",
  4: "EnemyDamageShrineUpgrade",
  5: "EnemySpeedShrineUpgrade",
  6: "EnemyShieldShrineUpgrade",
  7: "EnemyCountShrineUpgrade",
  8: "EnemyRespawnShrineUpgrade",
  9: "NextBiomeEnemyShrineUpgrade",
  10: "BiomeSpeedShrineUpgrade",
  11: "MinibossCountShrineUpgrade",
  12: "BossDifficultyShrineUpgrade",
  13: "BoonSkipShrineUpgrade",
  14: "BoonManaReserveShrineUpgrade",
  15: "BanUnpickedBoonsShrineUpgrade",
  16: "LimitGraspShrineUpgrade",
  17: "EnemyEliteShrineUpgrade",
};
